version: '3.9'
services:
  backend:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
  database:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ambassador
      - MYSQL_USER=root_nestjs
      - MYSQL_PASSWORD=password
      - MYSQL_TCP_PORT=3306
